version: "3.8"
services:
    www:
        build: .
        ports: 
            - "8000:80"
        volumes:
            - ./pagina:/var/www/html
        links:
            - database
        networks:
            - default
    database:
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: basededatos
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./contenido:/docker-entrypoint-initdb.d
            - ./configuracion:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - database:database
        ports:
            - 8001:80
        environment:
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent:
